name: publish

on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+"
jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/keinercx/microservices/users:$GITHUB_SHA
          docker push ghcr.io/keinercx/microservices/users:$GITHUB_SHA
